version: 3
metadata_directory: metadata
services:
  mailhog:
    port: 8025
  hasura:
    version: v2.8.0
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
  auth:
    version: 0.10.0
  storage:
    version: 0.2.3
  minio:
    environment:
      minio_root_password: minioaccesskey123123
      minio_root_user: minioaccesskey123123
  postgres:
    environment:
      postgres_password: postgres
      postgres_user: postgres
auth:
  access_control:
    email:
      allowed_email_domains: ''
      allowed_emails: ''
      blocked_email_domains: ''
      blocked_emails: ''
    allowed_redirect_urls: ''
  anonymous_users:
    enabled: true
  client_url: http://localhost:3000
  disable_new_users: false
  email:
    passwordless:
      enabled: true
    signin_email_verified_required: true
    template:
      fetch_url: ''
  gravatar:
    default: ''
    enabled: true
    rating: ''
  locale:
    allowed_locales: en
    default: en
  password:
    hibp:
      enabled: false
    min_length: 3
  provider:
    apple:
      enabled: false
      client_id: ''
      key_id: ''
      private_key: ''
      scope: name,email
      team_id: ''
    bitbucket:
      enabled: false
      client_id: ''
      client_secret: ''
    facebook:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: email,photos,displayName
    github:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: user:email
      token_url: ''
      user_profile_url: ''
    gitlab:
      enabled: false
      base_url: ''
      client_id: ''
      client_secret: ''
      scope: read_user
    google:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: email,profile
    linkedin:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: r_emailaddress,r_liteprofile
    spotify:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: user-read-email,user-read-private
    strava:
      enabled: false
      client_id: ''
      client_secret: ''
    twilio:
      enabled: false
      account_sid: ''
      auth_token: ''
      messaging_service_id: ''
    twitter:
      enabled: false
      consumer_key: ''
      consumer_secret: ''
    windows_live:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: wl.basic,wl.emails,wl.contacts_emails
  sms:
    passwordless:
      enabled: false
    provider: null
    twilio:
      account_sid: ''
      auth_token: ''
      from: ''
      messaging_service_id: ''
  smtp:
    host: nhost_mailhog
    auth_method: ''
    pass: password
    port: 1807
    secure: false
    sender: hasura-auth@example.com
    user: user
  access_token:
    expires_in: 900
  refresh_token:
    expires_in: 43200
  user:
    default_allowed_roles: user,me
    default_role: user
  mfa:
    enabled: true
    totp_issuer: nhost
